name: blog_sigre
version: 0.0.1
description: Material Design Lite 'MDL Blog Template'
author: <Sigre> <hirayamaru@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl: '>=1.0.0 <2.0.0'

  logging: any
  logging_handlers: any
  console_log_handler: any

  di: any

transformers:
  - di
